// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlnYgBDpkWX2KlvFaG3Wo3xHTaSaBPLdM',
    appId: '1:899880472170:web:d26145215202740264c413',
    messagingSenderId: '899880472170',
    projectId: 'rideaway-40834',
    authDomain: 'rideaway-40834.firebaseapp.com',
    storageBucket: 'rideaway-40834.firebasestorage.app',
    measurementId: 'G-97RQ8GMBZ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsrjkYor93tZ63iZl2kKaUdcft5cydnc0',
    appId: '1:899880472170:android:430a820658ed266264c413',
    messagingSenderId: '899880472170',
    projectId: 'rideaway-40834',
    storageBucket: 'rideaway-40834.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRYZKm2dBA3Oy4KCfkZ_uOTGnIjKQ3W80',
    appId: '1:899880472170:ios:b160d63af9c58c0764c413',
    messagingSenderId: '899880472170',
    projectId: 'rideaway-40834',
    storageBucket: 'rideaway-40834.firebasestorage.app',
    iosBundleId: 'com.example.rideaway',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRYZKm2dBA3Oy4KCfkZ_uOTGnIjKQ3W80',
    appId: '1:899880472170:ios:b160d63af9c58c0764c413',
    messagingSenderId: '899880472170',
    projectId: 'rideaway-40834',
    storageBucket: 'rideaway-40834.firebasestorage.app',
    iosBundleId: 'com.example.rideaway',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlnYgBDpkWX2KlvFaG3Wo3xHTaSaBPLdM',
    appId: '1:899880472170:web:cf5307781369720664c413',
    messagingSenderId: '899880472170',
    projectId: 'rideaway-40834',
    authDomain: 'rideaway-40834.firebaseapp.com',
    storageBucket: 'rideaway-40834.firebasestorage.app',
    measurementId: 'G-K1L9969HBE',
  );
}
